
services:
  logserver:
    build: ./flask_logging_server/.
    volumes:
      - shared_data:/app
    networks:
      custom_network:
        ipv4_address: 172.28.0.2
    ports:
      - "5000:5000"
    depends_on:
        - dicomhawk
 
  dicomhawk:
    environment:
      - ENABLE_LOGGING= ${ENABLE_LOGGING}
      - Docker_ENV= ${Docker_ENV}
    build: ./dicom_server/.
    volumes:
      - shared_data:/app
    ports:
      - "11112:11112"
    networks:
      custom_network:
        ipv4_address: 172.28.0.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11112/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  shared_data:
    driver: local
 
 
networks:
  custom_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1