input {
  file {
    path => "/app/logs/simplified/simplified_logger.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "dicom_simplified"
  }
  file {
    path => "/app/logs/pynetdicom/pynetdicom.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "dicom_full"
  }
  file {
    path => "/app/logs/api_logs.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "api"
  }
  file {
    path => "/app/logs/reputation.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "reputation"
  }
  file {
    path => "/app/logs/scanned_ips.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "scanned_ips"
  }
  file {
    path => "/app/logs/exceptions/exceptions.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "exceptions"
  }
}

output {
  if [type] == "api" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "api_data-%{+YYYY.MM.dd}"
    }
  } else if [type] == "dicom_simplified" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "dicom_simplified-%{+YYYY.MM.dd}"
    }
  } else if [type] == "dicom_full" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "dicom_full-%{+YYYY.MM.dd}"
    }
  } else if [type] == "reputation" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "reputation-%{+YYYY.MM.dd}"
    }
  } else if [type] == "scanned_ips" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "scanned_ips-%{+YYYY.MM.dd}"
    }
  } else if [type] == "exceptions" {
    elasticsearch {
      hosts => ["172.18.0.3:9200"]
      index => "exceptions-%{+YYYY.MM.dd}"
    }
  }
}
